apiVersion: v1
kind: Pod
metadata:
  name: hello-nodejs
  labels:
    app: hello-nodejs
    tier: backend
    environment: dev
spec:
  containers:
    - name: hello-nodejs
      image: heliandro/hello-nodejs:v0.1.2
      imagePullPolicy: Always
      ports:
        - containerPort: 3001
      env:
        - name: PORT
          value: "3001"
