apiVersion: v1
kind: Service
metadata:
  name: my-service-nodeport
spec:
  type: NodePort
  selector:
    app: hello-nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
      nodePort: 30000